### ISSUE TITLE
Unable to install library - "Missing dependencies, please check reactbundle"

### ISSUE THREAD

**Issue by asdf1234-deleted** [Icinga/icingaweb2-module-reactbundle#8]
I saw there were a few new dependencies listed with Director after `v1.7.2`. I tried to install the primary culprit of the below error, but I am still facing an issue.I know this requires a certain php version, so I did try `scl enable`.

Issue:
```
[root@udaicinga-dev modules]# MODULE_NAME=reactbundle
[root@udaicinga-dev modules]# MODULE_VERSION=v0.6.0
[root@udaicinga-dev modules]# REPO="https://github.com/Icinga/icingaweb2-module-${MODULE_NAME}"
[root@udaicinga-dev modules]# MODULES_PATH="/usr/share/icingaweb2/modules"
[root@udaicinga-dev modules]# git clone ${REPO} "${MODULES_PATH}/${MODULE_NAME}" --branch "${MODULE_VERSION}"
Cloning into '/usr/share/icingaweb2/modules/reactbundle'...
remote: Enumerating objects: 205, done.
remote: Counting objects: 100% (205/205), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 2019 (delta 51), reused 176 (delta 27), pack-reused 1814
Receiving objects: 100% (2019/2019), 1.24 MiB | 0 bytes/s, done.
Resolving deltas: 100% (739/739), done.
Note: checking out '5a3751d175e97c352e255834e56509de06fef632'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

[root@udaicinga-dev modules]# icingacli module enable "${MODULE_NAME}"
Launching the run script /usr/share/icingaweb2/modules/director/run.php for module director failed with the following exception: Missing dependencies, please check reactbundle
```

Also tried:
```
[root@udaicinga-dev modules]# scl enable rh-php71 "icingacli module enable reactbundle"
Launching the run script /usr/share/icingaweb2/modules/director/run.php for module director failed with the following exception: Missing dependencies, please check reactbundle
```

Is there a dependency I am missing?

PHP:
```
[root@udaicinga-dev modules]# /opt/rh/rh-php71/root/usr/sbin/php-fpm --version
PHP 7.1.30 (fpm-fcgi) (built: Jul 10 2019 09:46:42)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by asdf1234-deleted** [comment]
This seems to be a schema issue:
```
[root@udaicinga-dev modules]# psql -h "${DB_HOST}" -U director -d director -f "/usr/share/icingaweb2/modules/director/schema/pgsql.sql"

[root@udaicinga-dev modules]# icingacli module disable director
[root@udaicinga-dev modules]# icingacli module enable reactbundle
```

However, it's a bit of a chicken and the egg problem, since I normally rely on:
```
icingacli director migration pending --verbose
```

Which was failing with the original error. Also, I could not authenticate at all until I fixed the schema, so logging into Icingaweb2 to do a schema migration was a moot point:

![image](https://user-images.githubusercontent.com/27829577/69198070-7d1ac280-0b01-11ea-8df8-9ba99f634773.png)
![image](https://user-images.githubusercontent.com/27829577/69198119-ac313400-0b01-11ea-8652-0b220f8d0825.png)

**Comment by asdf1234-deleted** [comment]
Disregard, I believe this was a missing config directory
```
icingacli setup config directory --group icingaweb2;
```

... and also ensuring /etc/icingaweb2/enabledModules/ was clean on upgrade for when I enabled them again.

**Comment by peter-snr** [comment]
I have having some issues with icingacli during installation.  The command I am using is: -
```
icingacli module enable director
```
Which fails with this message...
```
Launching the run script /etc/icingaweb2/enabledModules/director/run.php for module director failed with the following exception: Missing dependencies, please check
```
I tried adding --debug at the end of the command but still exactly the same message?

So I tried the command above (see @mtdeguzis ), just in case it was not set up correctly, I was surprised to see the followilng error output from that command?

```
 icingacli setup config directory --group icingaweb2
USAGE: icingacli [module] <command> [action] [options]                                                                                                                                                                          [5/1900]
Available commands:                                                                                                                                                                                                                     
  help            Help for modules, commands and actions                                                                                                                                                                                  module          List and handle modules
  version         Shows version of Icinga Web 2, loaded modules and PHP
  web

Available modules:


Global options:

  --log [t]       Log to <t>, either stderr, file or syslog (default: stderr)
  --log-path <f>  Which file to log into in case of --log file
  --verbose       Be verbose
  --debug         Show debug output
  --help          Show help
  --benchmark     Show benchmark summary
  --watch [s]     Refresh output every <s> seconds (default: 5)
  --version       Shows version of Icinga Web 2, loaded modules and PHP
```
I am unable to figure out how to use icingacli from the help to fix my issue.  The options do not seem to work at all.

All the error message gives me is **Missing dependencies, please check** but unfortunately no further information, which dependencies would have been useful at this point.

Hope someone can help, two days on and no progress so far :(

**Comment by asdf1234-deleted** [comment]
@peter-snr  I would suggest a new issue on the director github portal instead of here, as my issue was regarding this module. Also check the readme file extensively.

https://github.com/Icinga/icingaweb2-module-director
https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md

I do agree it would be better to have a clearer debug message of what exactly is missing or wrong.

**Comment by Thomas-Gelf** [comment]
@lippserd: this looks like a side-effect of [#3771](https://github.com/Icinga/icingaweb2/issues/3771). `icingacli director` is expected to fail as long as there are missing dependencies, but this should not affect `icingacli module`. How should we deal with this?

**Comment by buggsdummy** [comment]
Don't clone, just download the zip of the version you're looking for, that works...
